include: package:extra_pedantic/analysis_options.yaml

linter:
  rules:
    prefer_single_quotes: true
    prefer_int_literals: true
    omit_local_variable_types: true
    avoid_classes_with_only_static_members: true
    prefer_constructors_over_static_methods: true
    lines_longer_than_80_chars: true
