name: yatta
description: A multipurpose YouTube frontend for hackers

publish_to: "none"

version: 0.0.2

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: 3.19.6

dependencies:
  autoscroll:
    path: package/autoscroll/
  fluent_ui: ^4.7.3
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  rss_dart:
    git:
      url: https://github.com/brainwo/rss.dart.git
      ref: "d74949d"
  shared_preferences: ^2.1.2
  url_launcher: ^6.1.11
  yaml_edit: ^2.2.0
  youtube_api:
    path: package/youtube_api/

dev_dependencies:
  custom_lint: ^0.6.4
  extra_pedantic: ^4.0.0
  flutter_test:
    sdk: flutter
  riverpod_lint: ^2.3.10
  test: ^1.21.0

flutter:
  uses-material-design: true
