name: yatta
description: A multipurpose YouTube frontend for hackers

publish_to: "none"

version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  fluent_ui: ^4.2.0
  flutter:
    sdk: flutter
  shared_preferences: ^2.1.2
  url_launcher: ^6.1.11
  youtube_api:
    path: ../youtube_api/

dev_dependencies:
  extra_pedantic: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
