name: youtube_api
description: YouTubeAPI is a plugin which directly interacts with YouTube
  server. Supports Searching video and playlist.
version: 1.0.3
homepage: https://github.com/brainwo/youtube_api
repository: https://github.com/brainwo/youtube_api

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  http: ^1.0.0
