name: Code check

on:
  push:
    branches:
      - main
    paths:
      - "**.dart"
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-flie: pubspec.yaml
      - name: Update dependencies
        run: flutter pub get
      - name: Disable analytics
        run: |
          flutter config --no-analytics
          dart --disable-analytics
      - name: Remove custom lint # https://github.com/invertase/dart_custom_lint/issues/228
        run: sed -i '/custom_lint/d' analysis_options.yaml
      - name: Format
        run: dart format --set-exit-if-changed lib
      - name: Analyze
        run: flutter analyze lib
